
// RootLayout Component
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Script from 'next/script';
import ClientWrapper from './components/clientlayout';
import Navbar from './components/NavBar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://kit.fontawesome.com/1f48a0d62b.js"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </head>
      <body className={`bg-white ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientWrapper>
          <Navbar />
          {children}
          <footer className="w-full bg-white text-black flex flex-col">
            <div className="bg-[#EEEFFB] py-6 sm:py-8 md:py-10">
              <div className="container mx-auto px-4 sm:px-6 md:px-8 lg:px-10">
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                  <div className="flex flex-col gap-6">
                    <h3 className="text-2xl sm:text-3xl md:text-4xl font-bold">ShopEasy</h3>
                    {/* <div className="flex flex-col sm:flex-row gap-2 w-full">
                      <input
                        type="text"
                        className="opacity-45 bg-[#FFFFFF] h-9 sm:h-10 px-3 sm:px-4 w-full sm:w-3/4"
                        placeholder="Enter Email Address"
                      />
                      <button
                        type="button"
                        className="rounded-[3px] h-9 sm:h-10 bg-[#FB2E86] w-full sm:w-1/4 text-white text-sm sm:text-base"
                      >
                        Sign Up
                      </button>
                    </div> */}
                    <div className="flex flex-col gap-2">
                      <p className="font-[Lato] font-normal text-sm sm:text-base text-[#8A8FB9]">
                        Contact Info
                      </p>
                      <p className="font-[Lato] font-normal text-sm sm:text-base text-[#8A8FB9]">
                        17 Princess Road, London, Greater London NW1 8JR, UK
                      </p>
                    </div>
                  </div>
                  <div className="flex flex-col gap-6">
                    <h3 className="font-[Josefin Sans] text-lg sm:text-xl md:text-2xl">Categories</h3>
                    <ul className="flex flex-col gap-3 sm:gap-4 font-[Lato] font-normal text-sm sm:text-base text-[#8A8FB9]">
                      <li className="cursor-pointer">Laptops & Computers</li>
                      <li className="cursor-pointer">Cameras & Photography</li>
                      <li className="cursor-pointer">Smart Phones & Tablets</li>
                      <li className="cursor-pointer">Video Games & Consoles</li>
                      <li className="cursor-pointer">Waterproof Headphones</li>
                    </ul>
                  </div>
                  <div className="flex flex-col gap-6">
                    <h3 className="font-[Josefin Sans] text-lg sm:text-xl md:text-2xl">Customer Care</h3>
                    <ul className="flex flex-col gap-3 sm:gap-4 font-[Lato] font-normal text-sm sm:text-base text-[#8A8FB9]">
                      <li className="cursor-pointer">My Account</li>
                      <li className="cursor-pointer">Discount</li>
                      <li className="cursor-pointer">Returns</li>
                      <li className="cursor-pointer">Orders History</li>
                      <li className="cursor-pointer">Order Tracking</li>
                    </ul>
                  </div>
                  <div className="flex flex-col gap-6">
                    <h3 className="font-[Josefin Sans] text-lg sm:text-xl md:text-2xl">Pages</h3>
                    <ul className="flex flex-col gap-3 sm:gap-4 font-[Lato] font-normal text-sm sm:text-base text-[#8A8FB9]">
                      <li className="cursor-pointer">Blog</li>
                      <li className="cursor-pointer">Browse the Shop</li>
                      <li className="cursor-pointer">Category</li>
                      <li className="cursor-pointer">Pre-Built Pages</li>
                      <li className="cursor-pointer">Visual Composer Elements</li>
                      <li className="cursor-pointer">WooCommerce Pages</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div className="bg-[#E7E4F8] py-4">
              <div className="container mx-auto px-4 sm:px-6 md:px-8 lg:px-10 flex flex-col sm:flex-row justify-between items-center">
                <p className="font-[Lato] font-semibold text-sm sm:text-base text-[#9DA0AE]">
                  ©Webecy - All Rights Reserved
                </p>
                <div className="flex gap-4 mt-2 sm:mt-0">
                  <i className="fa-brands fa-facebook cursor-pointer text-xl sm:text-2xl"></i>
                  <i className="fa-brands fa-instagram cursor-pointer text-xl sm:text-2xl"></i>
                  <i className="fa-brands fa-twitter cursor-pointer text-xl sm:text-2xl"></i>
                </div>
              </div>
            </div>
          </footer>
        </ClientWrapper>
      </body>
    </html>
  );
}
